// Generated on 2013-07-10 using generator-angular 0.3.0
'use strict';
var LIVERELOAD_PORT = 35729;
var lrSnippet = require('connect-livereload')({ port: LIVERELOAD_PORT });
var mountFolder = function (connect, dir) {
  return connect.static(require('path').resolve(dir));
};

// # Globbing
// for performance reasons we're only matching one level down:
// 'test/spec/{,*/}*.js'
// use this if you want to recursively match all subfolders:
// 'test/spec/**/*.js'

module.exports = function (grunt) {
  // load all grunt tasks
  require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

  // configurable paths
  var appConfig = {
    app: 'app',
    dist: 'dist',
    tmp: '.tmp'
  };

  try {
    appConfig.app = require('./bower.json').appPath || appConfig.app;
  } catch (e) {}

  grunt.initConfig({
    config: appConfig,
    watch: {
      options: {
        livereload: LIVERELOAD_PORT
      },
      scritps: {
        files: [
          '<%= config.app %>/scripts/{,*/}*.js'
        ],
        livereload: true,
        tasks: ['jshint', 'clean:devScripts', 'copy:devScripts']
      },
      css: {
        files: [
          '<%= config.app %>/styles/{,*/}*.css'
        ],
        livereload: true,
        tasks: ['csslint', 'concat:cssDev', 'clean:devCss', 'copy:devCss', 'clean:cssBundle']
      },
      html: {
        files: [
          '<%= config.app %>/index.html',
          '<%= config.app %>/views/{,*/}*.html'
        ],
        livereload: true,
        tasks: ['clean:devHtml', 'copy:devHtml']
      },
      images: {
        files: [
          '<%= config.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}'
        ],
        livereload: true,
        tasks: ['clean:devImages', 'copy:devImages']
      }
    },
    connect: {
      options: {
        port: 9000,
        // Change this to '0.0.0.0' to access the server from outside.
        hostname: '0.0.0.0'
      },
      livereload: {
        options: {
          middleware: function (connect) {
            return [
              lrSnippet,
              mountFolder(connect, appConfig.tmp)
            ];
          }
        }
      },
      test: {
        options: {
          middleware: function (connect) {
            return [
              mountFolder(connect, appConfig.tmp),
              mountFolder(connect, 'test')
            ];
          }
        }
      },
      dist: {
        options: {
          middleware: function (connect) {
            return [
              mountFolder(connect, appConfig.dist)
            ];
          }
        }
      }
    },
    open: {
      server: {
        url: 'http://localhost:<%= connect.options.port %>'
      },
      e2e:{
        url: 'http://localhost:9876/__karma/'
      }
    },
    clean: {
      dist: {
        files: [{
          dot: true,
          src: [
            '<%= config.tmp %>',
            '<%= config.dist %>/*',
            '!<%= config.dist %>/.git*'
          ]
        }]
      },
      devScripts: [
        '<%= config.tmp %>/scripts/{,*/}*.js'
      ],
      devCss: [
        '<%= config.tmp %>/styles/{,*/}*.css'
      ],
      cssBundle: [
        '<%= config.app %>/styles/bundle.css'
      ],
      devHtml: [
        '<%= config.tmp %>/index.html',
        '<%= config.tmp %>/views/{,*/}*.html'
      ],
      devImages: [
        '<%= config.tmp %>/images/{,*/}'
      ],
      server: {
        files: [
          {
            dot: true,
            src: [
              '<%= config.tmp %>/*',
              '!<%= config.tmp %>/bower_components*'
            ]
          }
        ]
      }
    },
    jshint: {
      options: {
        jshintrc: '.jshintrc'
      },
      all: [
        // 'Gruntfile.js',
        '<%= config.app %>/scripts/{,*/}*.js'
      ]
    },
    csslint:{
      options: {
        //https://github.com/stubbornella/csslint/wiki/Rules
        csslintrc: '.csslintrc'
      },
      all:[
        '<%= config.tmp %>/styles/{,*/}*.css'
      ]
    },
    concat: {
      options: {
        separator: ''
      },
      cssDev: {
        options:{
          banner: '/* This file was auto-generated by \'grunt concat:cssDev\'. Do not edit it. All changes will be lost. */\n'
        },
        src: ['<%= config.tmp %>/styles/{,*/}*.css'],
        dest: '<%= config.app %>/styles/bundle.css'
      }
    },
    rev: {
      dist: {
        files: {
          src: [
            '<%= config.dist %>/scripts/{,*/}*.js',
            '<%= config.dist %>/styles/{,*/}*.css',
            '<%= config.dist %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
            '<%= config.dist %>/styles/fonts/*'
          ]
        }
      }
    },
    useminPrepare: {
      html: '<%= config.app %>/index.html',
      options: {
        dest: '<%= config.dist %>'
      }
    },
    usemin: {
      html: ['<%= config.dist %>/{,*/}*.html'],
      css: ['<%= config.dist %>/styles/{,*/}*.css'],
      options: {
        dirs: ['<%= config.dist %>']
      }
    },
    imagemin: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%= config.app %>/images',
          src: '{,*/}*.{png,jpg,jpeg}',
          dest: '<%= config.dist %>/images'
        }]
      }
    },
    cssmin: {
      // By default, your `index.html` <!-- Usemin Block --> will take care of
      // minification. This option is pre-configured if you do not wish to use
      // Usemin blocks.
      dist: {
        files: {
          '<%= config.dist %>/styles/bundle.css': [
            '<%= config.app %>/styles/{,*/}*.css'
          ]
        }
      }
    },
    htmlmin: {
      dist: {
        options: {
          /*removeCommentsFromCDATA: true,
          // https://github.com/config/grunt-usemin/issues/44
          //collapseWhitespace: true,
          collapseBooleanAttributes: true,
          removeAttributeQuotes: true,
          removeRedundantAttributes: true,
          useShortDoctype: true,
          removeEmptyAttributes: true,
          removeOptionalTags: true*/
        },
        files: [{
          expand: true,
          cwd: '<%= config.app %>',
          src: ['features/{,*/}/views/*.html', 'index.html'],
          dest: '<%= config.dist %>'
        }]
      }
    },
    // Put files not handled in other tasks here
    copy: {
      bowerComponents:{
        files: [
          {
            expand: true,
            dot: true,
            cwd: '<%= config.app %>',
            dest: '<%= config.tmp %>',
            src: [
              'bower_components/{,**/}*.js'
            ]
          }
        ]
      },
      devScripts:{
        files: [
          {
            expand: true,
            cwd: '<%= config.app %>',
            dest: '<%= config.tmp %>',
            src: [
              '<%= config.app %>/scripts/{,*/}*.js'
            ]
          }
        ]
      },
      devCss:{
        files: [
          {
            expand: true,
            cwd: '<%= config.app %>',
            dest: '<%= config.tmp %>',
            src: [
              'styles/bundle.css'
            ]
          }
        ]
      },
      devHtml:{
        files: [
          {
            expand: true,
            cwd: '<%= config.app %>',
            dest: '<%= config.tmp %>',
            src: [
              '<%= config.tmp %>/index.html',
              '<%= config.tmp %>/views/{,*/}*.html'
            ]
          }
        ]
      },
      devImages:{
        files: [
          {
            expand: true,
            cwd: '<%= config.app %>',
            dest: '<%= config.tmp %>',
            src: [
              'images/{,*/}*.{gif,webp,svg,jpg}'
            ]
          }
        ]
      },
      dev:{
        files: [
          {
            expand: true,
            dot: true,
            cwd: '<%= config.app %>',
            dest: '<%= config.tmp %>',
            src: [
              'index.html',
              '404.html',
              'features/**',
              '*.{ico,png,txt}',
              '.htaccess',
              'images/{,*/}*.{gif,webp,svg,jpg}',
              'styles/bundle.css'
            ]
          }
        ]
      },
      dist: {
        files: [{
          expand: true,
          dot: true,
          cwd: '<%= config.app %>',
          dest: '<%= config.dist %>',
          src: [
            '*.{ico,png,txt}',
            '.htaccess',
            'images/{,*/}*.{gif,webp,svg}',
            'styles/fonts/*',
            (function(){
              var dependenciesToCopyToDist = [];
              for(var dep in require('./bower.json').dependencies){
                dependenciesToCopyToDist.push('bower_components/'+dep+'/**');
              }
              return dependenciesToCopyToDist;
            }())
          ]
        }, {
          expand: true,
          cwd: '<%= config.tmp %>/images',
          dest: '<%= config.dist %>/images',
          src: [
            'generated/*'
          ]
        }]
      }
    },
    karma: {
      'run-unit-tests': {
        configFile: 'karma.conf.js'
      },
      'single-run-unit-tests': {
        configFile: 'karma.conf.js',
        options: {
          singleRun: true,
          autoWatch: false
        }
      },
      'run-e2e-tests': {
        configFile: 'karma-e2e.conf.js'
      },
      'single-run-e2e-tests': {
        configFile: 'karma-e2e.conf.js',
        options: {
          singleRun: true,
          autoWatch: false
        }
      }
    },
    ngmin: {
      dist: {
        files: [
          {
            expand: true,
            cwd: '<%= config.dist %>/scripts/',
            src: '*.js',
            dest: '<%= config.dist %>/scripts/'
          }
        ]
      }
    },
    uglify: {
      dist: {
        files: {
          '<%= config.dist %>/scripts/scripts.js': [
            '<%= config.dist %>/scripts/scripts.js'
          ]
        }
      }
    }
  });

  grunt.loadTasks('grunt-tasks');

  grunt.registerTask('server', function (target) {
    if (target === 'dist') {
      return grunt.task.run(['build', 'open:server', 'connect:dist:keepalive']);
    }

    grunt.task.run([
      'jshint',
      'csslint',
      'concat:cssDev',
      'clean:server',
      'connect:livereload',
      'open:server',
      'copy:bowerComponents',
      'copy:dev',
      'clean:cssBundle',
      'watch'
    ]);
  });

  grunt.registerTask('run-unit-tests', [
    'karma:run-unit-tests'
  ]);

  grunt.registerTask('run-e2e-tests', [
    'connect:test',
    'karma:run-e2e-tests'
  ]);

  grunt.registerTask('single-run-e2e-tests', [
    'connect:test',
    'karma:single-run-e2e-tests'
  ]);

  grunt.registerTask('single-run-unit-tests', [
    'connect:test',
    'karma:single-run-unit-tests'
  ]);

  grunt.registerTask('build', [
    'clean:dist',
    'useminPrepare',
    'concat',
    'copy:dist',
    'ngmin',
    'cssmin:dist',
    'rev',
    'usemin'
  ]);

  grunt.registerTask('default', [
    'jshint',
    'test',
    'build'
  ]);

  grunt.registerTask('test', [
    'connect:livereload',
    'copy:appcache',
    'watch'
  ]);
};
